source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '13.0'

target 'App' do
  use_frameworks!
  pod 'Login', :path => '../mod/Login'
  pod 'LoginUI', :path => '../mod/LoginUI'
  pod 'MPAK', :path => '../mod/MPAK'
  pod 'Net', :path => '../mod/Net'
end
