name: MM
options:
    bundleIdPrefix: org.hi-tech
targets:
    App:
        type: application
        platform: iOS
        deploymentTarget: "13.0"
        sources:
            - path: "../src"
        settings:
            base:
                INFOPLIST_FILE: Info.plist
