name: IM
options:
    bundleIdPrefix: su.koren
targets:
    App:
        type: application
        platform: iOS
        deploymentTarget: "13.0"
        sources:
            - path: "../src"
        settings:
            base:
                INFOPLIST_FILE: Info.plist
